# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Backtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_backtest(object):
    def setupUi(self, backtest):
        backtest.setObjectName("backtest")
        backtest.resize(1722, 929)
        self.label3re1 = QtWidgets.QLabel(backtest)
        self.label3re1.setGeometry(QtCore.QRect(40, 84, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.label3re1.setFont(font)
        self.label3re1.setStyleSheet("color:white;")
        self.label3re1.setObjectName("label3re1")
        self.tilde3 = QtWidgets.QLabel(backtest)
        self.tilde3.setGeometry(QtCore.QRect(330, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tilde3.setFont(font)
        self.tilde3.setStyleSheet("color:white;")
        self.tilde3.setObjectName("tilde3")
        self.back_ans = QtWidgets.QTextBrowser(backtest)
        self.back_ans.setGeometry(QtCore.QRect(1470, 250, 231, 611))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.back_ans.setFont(font)
        self.back_ans.setStyleSheet("font: 11pt \"微軟正黑體\";")
        self.back_ans.setObjectName("back_ans")
        self.close_button = QtWidgets.QPushButton(backtest)
        self.close_button.setGeometry(QtCore.QRect(1590, 870, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton{\n"
"background:#6699CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid #DEF748;\n"
"background:#66A6FF;\n"
"}")
        self.close_button.setObjectName("close_button")
        self.labelre38_2 = QtWidgets.QLabel(backtest)
        self.labelre38_2.setGeometry(QtCore.QRect(40, 165, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.labelre38_2.setFont(font)
        self.labelre38_2.setStyleSheet("color:white;")
        self.labelre38_2.setObjectName("labelre38_2")
        self.LongMaText = QtWidgets.QLabel(backtest)
        self.LongMaText.setGeometry(QtCore.QRect(350, 164, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.LongMaText.setFont(font)
        self.LongMaText.setStyleSheet("color:white;")
        self.LongMaText.setObjectName("LongMaText")
        self.tilde1 = QtWidgets.QLabel(backtest)
        self.tilde1.setGeometry(QtCore.QRect(270, 173, 16, 16))
        self.tilde1.setStyleSheet("color:white;")
        self.tilde1.setObjectName("tilde1")
        self.backDate = QtWidgets.QDateEdit(backtest)
        self.backDate.setGeometry(QtCore.QRect(370, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.backDate.setFont(font)
        self.backDate.setStyleSheet("QDateEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QDateEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.backDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.backDate.setObjectName("backDate")
        self.labelre32 = QtWidgets.QLabel(backtest)
        self.labelre32.setGeometry(QtCore.QRect(40, 128, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.labelre32.setFont(font)
        self.labelre32.setStyleSheet("color:white;")
        self.labelre32.setObjectName("labelre32")
        self.shart_ma_low = QtWidgets.QLineEdit(backtest)
        self.shart_ma_low.setGeometry(QtCore.QRect(230, 166, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.shart_ma_low.setFont(font)
        self.shart_ma_low.setStyleSheet("QLineEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QLineEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.shart_ma_low.setObjectName("shart_ma_low")
        self.tall_ma_low = QtWidgets.QLineEdit(backtest)
        self.tall_ma_low.setGeometry(QtCore.QRect(420, 166, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.tall_ma_low.setFont(font)
        self.tall_ma_low.setStyleSheet("QLineEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QLineEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.tall_ma_low.setObjectName("tall_ma_low")
        self.frontDate = QtWidgets.QDateEdit(backtest)
        self.frontDate.setGeometry(QtCore.QRect(160, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.frontDate.setFont(font)
        self.frontDate.setStyleSheet("QDateEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QDateEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.frontDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.frontDate.setObjectName("frontDate")
        self.labelre38 = QtWidgets.QLabel(backtest)
        self.labelre38.setGeometry(QtCore.QRect(40, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.labelre38.setFont(font)
        self.labelre38.setStyleSheet("color:white;")
        self.labelre38.setObjectName("labelre38")
        self.start_back = QtWidgets.QPushButton(backtest)
        self.start_back.setGeometry(QtCore.QRect(1470, 870, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.start_back.setFont(font)
        self.start_back.setStyleSheet("QPushButton{\n"
"background:#6699CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid #DEF748;\n"
"background:#66A6FF;\n"
"}")
        self.start_back.setObjectName("start_back")
        self.shart_ma_high = QtWidgets.QLineEdit(backtest)
        self.shart_ma_high.setGeometry(QtCore.QRect(290, 166, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.shart_ma_high.setFont(font)
        self.shart_ma_high.setStyleSheet("QLineEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QLineEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.shart_ma_high.setObjectName("shart_ma_high")
        self.tilde2 = QtWidgets.QLabel(backtest)
        self.tilde2.setGeometry(QtCore.QRect(463, 163, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.tilde2.setFont(font)
        self.tilde2.setStyleSheet("color:white;")
        self.tilde2.setObjectName("tilde2")
        self.tall_ma_high = QtWidgets.QLineEdit(backtest)
        self.tall_ma_high.setGeometry(QtCore.QRect(490, 166, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.tall_ma_high.setFont(font)
        self.tall_ma_high.setStyleSheet("QLineEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QLineEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.tall_ma_high.setObjectName("tall_ma_high")
        self.Strategy = QtWidgets.QComboBox(backtest)
        self.Strategy.setGeometry(QtCore.QRect(130, 123, 291, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.Strategy.setFont(font)
        self.Strategy.setStyleSheet("QComboBox {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"\n"
"QComboBox:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.Strategy.setObjectName("Strategy")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.Strategy.addItem("")
        self.widget = QtWidgets.QWidget(backtest)
        self.widget.setGeometry(QtCore.QRect(40, 250, 1411, 651))
        self.widget.setStyleSheet("background:rgba(0,0,0,0.7);")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1411, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.PriceGraph_Button = QtWidgets.QPushButton(backtest)
        self.PriceGraph_Button.setGeometry(QtCore.QRect(1340, 197, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.PriceGraph_Button.setFont(font)
        self.PriceGraph_Button.setStyleSheet("QPushButton{\n"
"background:#6699CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid #DEF748;\n"
"background:#66A6FF;\n"
"}\n"
"")
        self.PriceGraph_Button.setObjectName("PriceGraph_Button")
        self.label = QtWidgets.QLabel(backtest)
        self.label.setGeometry(QtCore.QRect(840, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(backtest)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1721, 931))
        self.frame.setAccessibleDescription("")
        self.frame.setStyleSheet("border-image: url(\"backtestimage.jpg\");")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stock_number = QtWidgets.QLineEdit(backtest)
        self.stock_number.setGeometry(QtCore.QRect(130, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.stock_number.setFont(font)
        self.stock_number.setStyleSheet("QLineEdit {\n"
"border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"border-radius: 6px; /* 边框圆角 */\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"}\n"
"QLineEdit:hover { \n"
"border: 1px solid #298DFF;\n"
"border-radius: 6px;\n"
"padding-left: 5px; /* 文本距离左边界有5px */\n"
"background-color: #F2F2F2;\n"
"color: #298DFF;\n"
"selection-background-color: #298DFF;\n"
"selection-color: #F2F2F2;\n"
"}")
        self.stock_number.setObjectName("stock_number")
        self.ShortMaText = QtWidgets.QLabel(backtest)
        self.ShortMaText.setEnabled(True)
        self.ShortMaText.setGeometry(QtCore.QRect(160, 166, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.ShortMaText.setFont(font)
        self.ShortMaText.setStyleSheet("color:white;")
        self.ShortMaText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ShortMaText.setObjectName("ShortMaText")
        self.PricePoint_btn = QtWidgets.QPushButton(backtest)
        self.PricePoint_btn.setGeometry(QtCore.QRect(1210, 197, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        self.PricePoint_btn.setFont(font)
        self.PricePoint_btn.setStyleSheet("QPushButton{\n"
"background:#6699CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid #DEF748;\n"
"background:#66A6FF;\n"
"}\n"
"")
        self.PricePoint_btn.setObjectName("PricePoint_btn")
        self.frame.raise_()
        self.label3re1.raise_()
        self.tilde3.raise_()
        self.back_ans.raise_()
        self.close_button.raise_()
        self.labelre38_2.raise_()
        self.LongMaText.raise_()
        self.tilde1.raise_()
        self.backDate.raise_()
        self.labelre32.raise_()
        self.shart_ma_low.raise_()
        self.tall_ma_low.raise_()
        self.frontDate.raise_()
        self.labelre38.raise_()
        self.start_back.raise_()
        self.shart_ma_high.raise_()
        self.tilde2.raise_()
        self.tall_ma_high.raise_()
        self.Strategy.raise_()
        self.widget.raise_()
        self.PriceGraph_Button.raise_()
        self.label.raise_()
        self.stock_number.raise_()
        self.ShortMaText.raise_()
        self.PricePoint_btn.raise_()

        self.retranslateUi(backtest)
        QtCore.QMetaObject.connectSlotsByName(backtest)

    def retranslateUi(self, backtest):
        _translate = QtCore.QCoreApplication.translate
        backtest.setWindowTitle(_translate("backtest", "Form"))
        self.label3re1.setText(_translate("backtest", "選擇股票"))
        self.tilde3.setText(_translate("backtest", "~"))
        self.close_button.setText(_translate("backtest", "關閉"))
        self.labelre38_2.setText(_translate("backtest", "選擇策略參數"))
        self.LongMaText.setText(_translate("backtest", "長均線"))
        self.tilde1.setText(_translate("backtest", "~"))
        self.labelre32.setText(_translate("backtest", "選擇策略"))
        self.labelre38.setText(_translate("backtest", "選擇回測日期"))
        self.start_back.setText(_translate("backtest", "開始回測"))
        self.tilde2.setText(_translate("backtest", "~"))
        self.Strategy.setItemText(0, _translate("backtest", "請選擇策略"))
        self.Strategy.setItemText(1, _translate("backtest", "MA(均線)"))
        self.Strategy.setItemText(2, _translate("backtest", "RSI(相對強弱指標)"))
        self.Strategy.setItemText(3, _translate("backtest", "Boiling(布林通道)"))
        self.Strategy.setItemText(4, _translate("backtest", "MACD(指數平滑異同移動平均線)"))
        self.Strategy.setItemText(5, _translate("backtest", "KD(隨機指標)"))
        self.PriceGraph_Button.setText(_translate("backtest", "損益圖"))
        self.label.setText(_translate("backtest", "回測系統"))
        self.ShortMaText.setText(_translate("backtest", "短均線"))
        self.PricePoint_btn.setText(_translate("backtest", "買賣點"))
