# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'descripe.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_descripetion(object):
    def setupUi(self, descripetion):
        descripetion.setObjectName("descripetion")
        descripetion.resize(666, 558)
        descripetion.setStyleSheet("")
        self.textEdit = QtWidgets.QTextEdit(descripetion)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 641, 541))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color:white;\n"
"font: 9pt \"微軟正黑體\";\n"
"background:rgba(0,0,0,0.7);\n"
"border-radius:15px;")
        self.textEdit.setObjectName("textEdit")
        self.exit = QtWidgets.QPushButton(descripetion)
        self.exit.setGeometry(QtCore.QRect(280, 470, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton{\n"
"background:#6699CC;\n"
"color:#fff;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid #DEF748;\n"
"background:#66A6FF;\n"
"}\n"
"")
        self.exit.setObjectName("exit")

        self.retranslateUi(descripetion)
        QtCore.QMetaObject.connectSlotsByName(descripetion)

    def retranslateUi(self, descripetion):
        _translate = QtCore.QCoreApplication.translate
        descripetion.setWindowTitle(_translate("descripetion", "Form"))
        self.textEdit.setHtml(_translate("descripetion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">股票系統說明</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">________________________________</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">歡迎你來到股票系統</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">本系統能夠進行回測以及預測</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">回測日期為2000至最當日最新日期</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:600;\">預測將每日推薦漲跌</span></p></body></html>"))
        self.exit.setText(_translate("descripetion", "關閉"))
